### PR TITLE
Refactoring fast1.cpp

### PR DESCRIPTION
**Pull request by pr0kuk**
Improved codestyle and code visibility.
Integrating `fast1.cpp` into workflow...

### CODE REVIEW

**Comment by pr0kuk** [comment]
In `data/graph` there is a string with nodes' names, but I see it isn't used. Is it needed? @fasSstem

**Comment by fasSstem** [comment]
It isn't used, but it is supposed to be used in answer printing.

**Comment by fasSstem** [comment]
> It isn't used, but it is supposed to be used in answer printing.

**Comment by fasSstem** [comment]
> In `data/graph` there is a string with nodes' names, but I see it isn't used. Is it needed? @fasSstem

It isn't used, but it is supposed to be used in answer printing.

**Comment by fasSstem** [comment]
> In `data/graph` there is a string with nodes' names, but I see it isn't used. Is it needed? @fasSstem

It isn't used, but it is supposed to be used in answer printing.

**Pull request merged**
